services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile

    container_name: nginx

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - mysql

    networks:
      - projet-network

  mysql:
    image: mysql:8.0

    container_name: mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: R00t!2026_Docker
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: WP!2026_Database

    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    networks:
      - projet-network

networks:
  projet-network:
    driver: bridge

volumes:
  mysql_data: