services:

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile

    container_name: nginx

    restart: unless-stopped

    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - mysql

    networks:
      - projet-network

  mysql:
    image: mysql:8.0

    container_name: mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSwORD}

    volumes:
      - mysql_data:/var/lib/mysql
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

    networks:
      - projet-network