server {
    listen 80;
    server_name projetdocker.local;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name projetdocker.local;

    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    ssl_protocols TLSv1.2 TLSv1.3;

    server_tokens off;

    location / {
        return 200 "Nginx Infrastructure OK\n";
        add_header Content-Type text/plain;
    }
}